# Generated by Django 3.2.4 on 2021-07-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quote',
            table='quotes',
        ),
    ]
